### ISSUE TITLE
Virus Detected (Trojan) by Windows

### ISSUE THREAD

**Issue by Z3R0Presence** [Luke100000/Man-of-Many-Planes#1]
Windows Defender Detected a virus in the mod.

Version 0.0.3 1.20.1
![image](https://github.com/Luke100000/Man-of-Many-Planes/assets/102984898/6f229e7c-1401-416e-a562-614717994586)

Is This a real threat or just Windows Defender being Windows Defender?

**Comment by Luke100000** [comment]
A false positive. Is there any additional information, like, what exactly Windows Defender sees?

VirusTotal at least is happy, and they are much more trustworthy: https://www.virustotal.com/gui/file/7ea19bed04a41382fbda27044ba9bcc45e66cddab924098c496332c85f38eeef

Let's merge with https://github.com/Luke100000/ImmersiveAircraft/issues/140 as I think Immersive Aircraft itself is causing this.

**Comment by Z3R0Presence** [comment]
no, all the info that i was shown was that and it was auto placed into quarantine. Thanks for the quick reply, Only getting the alert from this mod though.

The Learn More is just the link to what the issue is thought to be:
https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3AScript%2FWacatac.B!ml&threatid=2147735503
