### ISSUE TITLE
Man of Many Planes crashed world when placing economy plance 1.20.1 - man_of_many_planes-0.1.0+1.20.1-forge.jar

### ISSUE THREAD

**Issue by ionutsoran** [Luke100000/Man-of-Many-Planes#8]
World crashes when trying to place economy plane. Something related to the rendering of the plane
I have put a paste bin here with the error to take a look if you have time!
Thanks!

https://pastebin.com/aScbqRYY

**Comment by Luke100000** [comment]
Man of Many Planes is very outdated and relies on an older version of Aircraft (0.7.5)
